// database.js - Drug Infusion Database
// Gerado automaticamente em: 2026-02-18 10:45:45
// NÃO EDITE MANUALMENTE - Use o script excel_to_database.py

export const rawDrugDatabase = {
    acido_tranexamico_bolus: {
        drug_key: "acido_tranexamico_bolus",
        group_key: "acido_tranexamico",
        calc_type: "bolus",
        name: "Ácido Tranexâmico",
        brand_name: "Transamin",
        category: "Coagulação",
        presentation: "05mL - 100mg/mL - 500mg",
        dose_unit: "mg/kg",
        default_quantity_unit: "mg",
        default_quantity: 1000,
        default_volume: 100,
        dose_range_text: "10-15 mg/kg",
        dose_min: 10,
        dose_max: 15,
        bolus_type: "diluted",
        has_presentation_selector: false,
        notes: "A velocidade é calculada para infusão em 20 minutos e não ultrapassar 100mg/min."
    },
    acido_tranexamico_manutencao: {
        drug_key: "acido_tranexamico_manutencao",
        group_key: "acido_tranexamico",
        calc_type: "infusion",
        name: "Ácido Tranexâmico",
        brand_name: "Transamin",
        category: "Coagulação",
        presentation: "05mL - 100mg/mL - 500mg",
        dose_unit: "mg/kg/h",
        default_quantity_unit: "mg",
        default_quantity: 1000,
        default_volume: 100,
        dose_range_text: "1-5 mg/kg/h",
        dose_min: 1,
        dose_max: 5,
        has_presentation_selector: false
    },
    adrenalina: {
        drug_key: "adrenalina",
        group_key: "adrenalina",
        calc_type: "infusion",
        name: "Adrenalina",
        category: "Drogas Vasoativas",
        presentation: "01mL - 01mg/mL - 01mg",
        dose_unit: "mcg/kg/min",
        default_quantity_unit: "mg",
        default_quantity: 10,
        default_volume: 100,
        dose_range_text: "0.1-2.0 mcg/kg/min",
        dose_min: 0.1,
        dose_max: 2,
        has_presentation_selector: false
    },
    dexmedetomidina_bolus: {
        drug_key: "dexmedetomidina_bolus",
        group_key: "dexmedetomidina",
        calc_type: "bolus",
        name: "Dexmedetomidina",
        brand_name: "Precedex",
        category: "Anestésicos e Sedativos",
        presentation: "02mL - 100mcg/mL - 200mcg",
        dose_unit: "mcg/kg",
        default_quantity_unit: "mcg",
        default_quantity: 200,
        default_volume: 100,
        dose_range_text: "1 mcg/kg",
        dose_min: 1,
        dose_max: 1,
        bolus_type: "diluted",
        has_presentation_selector: false,
        notes: "A velocidade é calculada para infusão em 10 ou 20 minutos."
    },
    dexmedetomidina_infusao: {
        drug_key: "dexmedetomidina_infusao",
        group_key: "dexmedetomidina",
        calc_type: "infusion",
        name: "Dexmedetomidina",
        brand_name: "Precedex",
        category: "Anestésicos e Sedativos",
        presentation: "02mL - 100mcg/mL - 200mcg",
        dose_unit: "mcg/kg/h",
        default_quantity_unit: "mcg",
        default_quantity: 200,
        default_volume: 100,
        dose_range_text: "0.1-0.7 mcg/kg/h",
        dose_min: 0.1,
        dose_max: 0.7,
        has_presentation_selector: false
    },
    dobutamina: {
        drug_key: "dobutamina",
        group_key: "dobutamina",
        calc_type: "infusion",
        name: "Dobutamina",
        brand_name: "Dobutrex",
        category: "Drogas Vasoativas",
        presentation: "20mL - 12.5mg/mL - 250mg",
        dose_unit: "mcg/kg/min",
        default_quantity_unit: "mg",
        default_quantity: 250,
        default_volume: 250,
        dose_range_text: "2.5-20 mcg/kg/min",
        dose_min: 2.5,
        dose_max: 20,
        has_presentation_selector: false
    },
    dopamina: {
        drug_key: "dopamina",
        group_key: "dopamina",
        calc_type: "infusion",
        name: "Dopamina",
        category: "Drogas Vasoativas",
        presentation: "10mL - 05mg/mL - 50mg",
        dose_unit: "mcg/kg/min",
        default_quantity_unit: "mg",
        default_quantity: 200,
        default_volume: 250,
        dose_range_text: "2-20 mcg/kg/min",
        dose_min: 2,
        dose_max: 20,
        has_presentation_selector: false
    },
    fentanil_bolus: {
        drug_key: "fentanil_bolus",
        group_key: "fentanil",
        calc_type: "bolus",
        name: "Fentanil",
        category: "Anestésicos e Sedativos",
        presentation: "05mL - 50mcg/mL - 250mcg",
        dose_unit: "mcg/kg",
        default_quantity_unit: "mcg",
        default_quantity: 250,
        default_volume: 5,
        dose_range_text: "1-5 mcg/kg",
        dose_min: 1,
        dose_max: 5,
        bolus_type: "direct",
        has_presentation_selector: true,
        presentation_options: [
            { quantity: 100, volume: 2, label: "02mL - 50mcg/mL - 100mcg" },
            { quantity: 250, volume: 5, label: "05mL - 50mcg/mL - 250mcg", isDefault: true },
            { quantity: 500, volume: 10, label: "10mL - 50mcg/mL - 500mcg" }
        ]
    },
    fentanil_infusao: {
        drug_key: "fentanil_infusao",
        group_key: "fentanil",
        calc_type: "infusion",
        name: "Fentanil",
        category: "Anestésicos e Sedativos",
        presentation: "05mL - 50mcg/mL - 250mcg",
        dose_unit: "mcg/kg/h",
        default_quantity_unit: "mcg",
        default_quantity: 500,
        default_volume: 100,
        dose_range_text: "1-3 mcg/kg/h",
        dose_min: 1,
        dose_max: 3,
        has_presentation_selector: true,
        presentation_options: [
            { quantity: 100, volume: 2, label: "02mL - 50mcg/mL - 100mcg" },
            { quantity: 250, volume: 5, label: "05mL - 50mcg/mL - 250mcg", isDefault: true },
            { quantity: 500, volume: 10, label: "10mL - 50mcg/mL - 500mcg" }
        ]
    },
    heparina_bolus: {
        drug_key: "heparina_bolus",
        group_key: "heparina",
        calc_type: "bolus",
        name: "Heparina NF",
        category: "Coagulação",
        presentation: "05mL - 5.000UI/mL - 25.000UI",
        dose_unit: "UI/kg",
        default_quantity_unit: "UI",
        default_quantity: 5000,
        default_volume: 10,
        dose_range_text: "50-100 UI/kg",
        dose_min: 50,
        dose_max: 100,
        bolus_type: "direct",
        has_presentation_selector: false,
        notes: "ANTÍDOTO: Protamina"
    },
    heparina_infusao: {
        drug_key: "heparina_infusao",
        group_key: "heparina",
        calc_type: "infusion",
        name: "Heparina NF",
        category: "Coagulação",
        presentation: "05mL - 5.000UI/mL - 25.000UI",
        dose_unit: "UI/kg/h",
        default_quantity_unit: "UI",
        default_quantity: 25000,
        default_volume: 250,
        dose_range_text: "10-25 UI/kg/h",
        dose_min: 10,
        dose_max: 25,
        has_presentation_selector: false,
        notes: "Ajustar dose de acordo com o TTPa"
    },
    ketamina_bolus: {
        drug_key: "ketamina_bolus",
        group_key: "ketamina",
        calc_type: "bolus",
        name: "Ketamina",
        category: "Anestésicos e Sedativos",
        presentation: "02mL - 50mg/mL - 100mg",
        dose_unit: "mg/kg",
        default_quantity_unit: "mg",
        default_quantity: 100,
        default_volume: 2,
        dose_range_text: "0.5-2 mg/kg",
        dose_min: 0.5,
        dose_max: 2,
        bolus_type: "direct",
        has_presentation_selector: true,
        presentation_options: [
            { quantity: 100, volume: 2, label: "02mL - 50mg/mL - 100mg", isDefault: true },
            { quantity: 500, volume: 10, label: "10mL - 50mg/mL - 500mg" }
        ]
    },
    ketamina_infusao: {
        drug_key: "ketamina_infusao",
        group_key: "ketamina",
        calc_type: "infusion",
        name: "Ketamina",
        category: "Anestésicos e Sedativos",
        presentation: "02mL - 50mg/mL - 100mg",
        dose_unit: "mg/kg/h",
        default_quantity_unit: "mg",
        default_quantity: 500,
        default_volume: 100,
        dose_range_text: "0.5-2 mg/kg/h",
        dose_min: 0.5,
        dose_max: 2,
        has_presentation_selector: true,
        presentation_options: [
            { quantity: 100, volume: 2, label: "02mL - 50mg/mL - 100mg", isDefault: true },
            { quantity: 500, volume: 10, label: "10mL - 50mg/mL - 500mg" }
        ]
    },
    midazolam_bolus: {
        drug_key: "midazolam_bolus",
        group_key: "midazolam",
        calc_type: "bolus",
        name: "Midazolam",
        category: "Anestésicos e Sedativos",
        presentation: "03mL - 05mg/mL - 15mg",
        dose_unit: "mg/kg",
        default_quantity_unit: "mg",
        default_quantity: 15,
        default_volume: 3,
        dose_range_text: "0.05-0.3 mg/kg",
        dose_min: 0.05,
        dose_max: 0.3,
        bolus_type: "direct",
        has_presentation_selector: true,
        presentation_options: [
            { quantity: 15, volume: 3, label: "03mL - 05mg/mL - 15mg", isDefault: true, concentration: 5 },
            { quantity: 5, volume: 5, label: "05mL - 01mg/mL - 05mg", concentration: 1 },
            { quantity: 50, volume: 10, label: "10mL - 05mg/mL - 50mg", concentration: 5 }
        ]
    },
    midazolam_infusao: {
        drug_key: "midazolam_infusao",
        group_key: "midazolam",
        calc_type: "infusion",
        name: "Midazolam",
        category: "Anestésicos e Sedativos",
        presentation: "03mL - 05mg/mL - 15mg",
        dose_unit: "mg/kg/h",
        default_quantity_unit: "mg",
        default_quantity: 50,
        default_volume: 50,
        dose_range_text: "0.05-0.4 mg/kg/h",
        dose_min: 0.05,
        dose_max: 0.4,
        has_presentation_selector: true,
        presentation_options: [
            { quantity: 15, volume: 3, label: "03mL - 05mg/mL - 15mg", isDefault: true, concentration: 5 },
            { quantity: 5, volume: 5, label: "05mL - 01mg/mL - 05mg", concentration: 1 },
            { quantity: 50, volume: 10, label: "10mL - 05mg/mL - 50mg", concentration: 5 }
        ]
    },
    milrinona_bolus: {
        drug_key: "milrinona_bolus",
        group_key: "milrinona",
        calc_type: "bolus",
        name: "Milrinona",
        brand_name: "Primacor",
        category: "Drogas Vasoativas",
        presentation: "10mL - 01mg/mL - 10mg",
        dose_unit: "mcg/kg",
        default_quantity_unit: "mg",
        default_quantity: 10,
        default_volume: 100,
        dose_range_text: "50 mcg/kg",
        dose_min: 50,
        dose_max: 50,
        bolus_type: "diluted",
        has_presentation_selector: false,
        notes: "Administrar em 10 minutos."
    },
    milrinona_infusao: {
        drug_key: "milrinona_infusao",
        group_key: "milrinona",
        calc_type: "infusion",
        name: "Milrinona",
        brand_name: "Primacor",
        category: "Drogas Vasoativas",
        presentation: "10mL - 01mg/mL - 10mg",
        dose_unit: "mcg/kg/min",
        default_quantity_unit: "mg",
        default_quantity: 10,
        default_volume: 100,
        dose_range_text: "0.375-0.75 mcg/kg/min",
        dose_min: 0.375,
        dose_max: 0.75,
        has_presentation_selector: false
    },
    nitroglicerina: {
        drug_key: "nitroglicerina",
        group_key: "nitroglicerina",
        calc_type: "infusion",
        name: "Nitroglicerina",
        brand_name: "Tridil",
        category: "Drogas Vasoativas",
        presentation: "10mL - 05mg/mL - 50mg",
        dose_unit: "mcg/min",
        default_quantity_unit: "mg",
        default_quantity: 50,
        default_volume: 250,
        dose_range_text: "5-200 mcg/min",
        dose_min: 5,
        dose_max: 200,
        has_presentation_selector: false,
        notes: "Dose NÃO é baseada em peso."
    },
    nitroprussiato: {
        drug_key: "nitroprussiato",
        group_key: "nitroprussiato",
        calc_type: "infusion",
        name: "Nitroprussiato de Sódio",
        brand_name: "Nipride",
        category: "Drogas Vasoativas",
        presentation: "02mL - 25mg/mL - 50mg",
        dose_unit: "mcg/kg/min",
        default_quantity_unit: "mg",
        default_quantity: 50,
        default_volume: 250,
        dose_range_text: "0.3-10 mcg/kg/min",
        dose_min: 0.3,
        dose_max: 10,
        has_presentation_selector: false,
        notes: "Proteger da luz."
    },
    noradrenalina: {
        drug_key: "noradrenalina",
        group_key: "noradrenalina",
        calc_type: "infusion",
        name: "Noradrenalina Base",
        category: "Drogas Vasoativas",
        presentation: "04mL - 01mg/mL - 04mg",
        dose_unit: "mcg/kg/min",
        default_quantity_unit: "mg",
        default_quantity: 4,
        default_volume: 250,
        dose_range_text: "0.1-0.5 mcg/kg/min",
        dose_min: 0.1,
        dose_max: 0.5,
        has_presentation_selector: false
    },
    propofol_bolus: {
        drug_key: "propofol_bolus",
        group_key: "propofol",
        calc_type: "bolus",
        name: "Propofol 1%",
        brand_name: "Diprivan",
        category: "Anestésicos e Sedativos",
        presentation: "20mL - 10mg/mL - 200mg",
        dose_unit: "mg/kg",
        default_quantity_unit: "mg",
        default_quantity: 200,
        default_volume: 20,
        dose_range_text: "0.5-2 mg/kg",
        dose_min: 0.5,
        dose_max: 2,
        bolus_type: "direct",
        has_presentation_selector: false
    },
    propofol_infusao: {
        drug_key: "propofol_infusao",
        group_key: "propofol",
        calc_type: "infusion",
        name: "Propofol 1%",
        brand_name: "Diprivan",
        category: "Anestésicos e Sedativos",
        presentation: "20mL - 10mg/mL - 200mg",
        dose_unit: "mg/kg/h",
        default_quantity_unit: "mg",
        default_quantity: 200,
        default_volume: 100,
        dose_range_text: "2-12 mg/kg/h",
        dose_min: 2,
        dose_max: 12,
        has_presentation_selector: false
    },
    remifentanil: {
        drug_key: "remifentanil",
        group_key: "remifentanil",
        calc_type: "infusion",
        name: "Remifentanil",
        brand_name: "Ultiva",
        category: "Anestésicos e Sedativos",
        presentation: "01 frasco = 02mg",
        dose_unit: "mcg/kg/min",
        default_quantity_unit: "mcg",
        default_quantity: 2000,
        default_volume: 50,
        dose_range_text: "0.05-2 mcg/kg/min",
        dose_min: 0.05,
        dose_max: 2,
        has_presentation_selector: false
    },
    rocuronio_bolus: {
        drug_key: "rocuronio_bolus",
        group_key: "rocuronio",
        calc_type: "bolus",
        name: "Rocurônio",
        brand_name: "Esmeron",
        category: "Bloqueadores Neuromusculares",
        presentation: "05mL - 10mg/mL - 50mg",
        dose_unit: "mg/kg",
        default_quantity_unit: "mg",
        default_quantity: 50,
        default_volume: 5,
        dose_range_text: "0.6-1.2 mg/kg",
        dose_min: 0.6,
        dose_max: 1.2,
        bolus_type: "direct",
        has_presentation_selector: false
    },
    rocuronio_infusao: {
        drug_key: "rocuronio_infusao",
        group_key: "rocuronio",
        calc_type: "infusion",
        name: "Rocurônio",
        brand_name: "Esmeron",
        category: "Bloqueadores Neuromusculares",
        presentation: "05mL - 10mg/mL - 50mg",
        dose_unit: "mcg/kg/min",
        default_quantity_unit: "mg",
        default_quantity: 50,
        default_volume: 50,
        dose_range_text: "5-12 mcg/kg/min",
        dose_min: 5,
        dose_max: 12,
        has_presentation_selector: false
    },
    sulfato_magnesio_bolus: {
        drug_key: "sulfato_magnesio_bolus",
        group_key: "sulfato_magnesio",
        calc_type: "bolus",
        name: "Sulfato de Magnésio",
        category: "Outras Drogas",
        presentation: "10% ou 50%",
        dose_unit: "mg/kg",
        default_quantity_unit: "mg",
        default_quantity: 5000,
        default_volume: 100,
        dose_range_text: "30-50 mg/kg",
        dose_min: 30,
        dose_max: 50,
        bolus_type: "diluted",
        has_presentation_selector: true,
        presentation_options: [
            { quantity: 5000, volume: 100, label: "50% (5g/10mL)", value: "50", isDefault: true },
            { quantity: 1000, volume: 100, label: "10% (1g/10mL)", value: "10" }
        ],
        notes: "Administrar em 15 minutos."
    },
    sulfato_magnesio_infusao: {
        drug_key: "sulfato_magnesio_infusao",
        group_key: "sulfato_magnesio",
        calc_type: "infusion",
        name: "Sulfato de Magnésio",
        category: "Outras Drogas",
        presentation: "10% ou 50%",
        dose_unit: "mg/kg/h",
        default_quantity_unit: "mg",
        default_quantity: 5000,
        default_volume: 100,
        dose_range_text: "15-30 mg/kg/h",
        dose_min: 15,
        dose_max: 30,
        has_presentation_selector: true,
        presentation_options: [
            { quantity: 5000, volume: 100, label: "50% (5g/10mL)", value: "50", isDefault: true },
            { quantity: 1000, volume: 100, label: "10% (1g/10mL)", value: "10" }
        ]
    },
    vasopressina: {
        drug_key: "vasopressina",
        group_key: "vasopressina",
        calc_type: "infusion",
        name: "Vasopressina",
        brand_name: "Encrise",
        category: "Drogas Vasoativas",
        presentation: "01mL - 20U/mL - 20U",
        dose_unit: "U/min",
        default_quantity_unit: "U",
        default_quantity: 20,
        default_volume: 100,
        dose_range_text: "0.01-0.04 U/min",
        dose_min: 0.01,
        dose_max: 0.04,
        has_presentation_selector: false,
        notes: "Dose NÃO é baseada em peso."
    },
};
